export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    USER_DATA_DELETED: "PROFILE_DATA_DELETED",
  },
  blog: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    BLOG_DATA_EDITED: "BOLOG_DATA_EDITED",
    BLOG_DATA_DELETED: "BOLOG_DATA_DELETED",
    BLOG_DATA_LINKED: "BOLOG_DATA_LINKED",
    BLOG_DATA_COMMENTED: "BOLOG_DATA_COMMENTED",
    BLOG_DATA_FAVOURITED: "BOLOG_DATA_FAVOURITED",
    BLOG_DATA_CREATE: "BOLOG_DATA_CREATE",
    BLOG_DATA_SINGLE_BLOG: "BLOG_DATA_SINGLE_BLOG",
  },
};
